document.addEventListener('DOMContentLoaded',()=>{
'use strict';
const K={appointments:'lumiHairAppointments',clients:'lumiHairClients',settings:'lumiHairSettings',services:'lumiHairServices',legacy:'lumiHairBookings'};
const DEF={masterName:'LUMI HAIR',phone:'+7 (999) 000-00-00',address:'Ваш город, ваш адрес',startTime:'10:00',endTime:'20:00',slotDuration:30,advanceBooking:30,site:{heroLabel:'Кератин • Уход • Восстановление',heroTitle:'Волосы, к которым хочется прикасаться',heroAccent:'к которым хочется прикасаться',heroText:'Профессиональный уход за волосами, который возвращает гладкость, блеск и ухоженный вид без лишней суеты.',heroButton:'Записаться онлайн',heroSecondaryButton:'Смотреть работы',heroNote:'Индивидуальный подбор процедуры для каждого типа волос',heroStat:'100%',heroStatText:'внимания вашим волосам',aboutLabel:'Обо мне',aboutTitle:'Красивые волосы —',aboutAccent:'это не роскошь',aboutText1:'Я создаю не просто красивый визуальный результат, а комфортный уход, который помогает вам чувствовать себя уверенно каждый день.',aboutText2:'Перед процедурой мы обсуждаем состояние волос, желаемый результат и подбираем оптимальный вариант ухода.',aboutSignature:'С заботой о ваших волосах',heroImage:'',aboutImage:'',contactText:'Есть вопрос или хотите подобрать процедуру? Свяжитесь со мной удобным способом.',seoTitle:'LUMI HAIR — Кератиновое выпрямление и уход за волосами',seoDescription:'LUMI HAIR — кератиновое выпрямление, восстановление и уход за волосами. Запись онлайн.',benefits:[{number:'01',title:'Индивидуальный подход',text:'Подбираю процедуру с учётом состояния и структуры волос.'},{number:'02',title:'Профессиональные составы',text:'Использую качественные средства для безопасного ухода.'},{number:'03',title:'Красивый результат',text:'Гладкость, блеск и ухоженный внешний вид волос.'}],portfolio:[{category:'Кератин',title:'Гладкость и блеск'},{category:'Восстановление',title:'Ухоженные волосы'},{category:'Уход',title:'Естественный блеск'},{category:'Кератин',title:'До / После'}],reviews:[{name:'Анна',service:'Кератиновое выпрямление',text:'Волосы стали невероятно гладкими и блестящими. Очень понравился результат, обязательно вернусь.'},{name:'Елена',service:'Восстановление',text:'Очень бережный подход. Мне подробно объяснили, какую процедуру лучше выбрать для моих волос.'},{name:'Мария',service:'Ботокс для волос',text:'Наконец-то нашла мастера, которому могу доверить свои волосы. Результат превзошёл ожидания.'}],faq:[{question:'Сколько длится процедура?',answer:'В среднем процедура занимает от 2 до 4 часов. Точное время зависит от длины и густоты волос.'},{question:'Можно ли делать процедуру на окрашенные волосы?',answer:'В большинстве случаев да. Перед процедурой мастер оценивает состояние волос и подбирает подходящий вариант ухода.'},{question:'Как подготовиться к процедуре?',answer:'Специальная подготовка обычно не требуется.'},{question:'Как записаться?',answer:'Нажмите «Записаться», выберите услугу, дату и свободное время, затем оставьте контакты.'}]}};
const DEFAULT_SERVICES=[{id:'service_keratin',name:'Кератиновое выпрямление',price:3500,duration:180,description:'Гладкие, блестящие и послушные волосы.',active:true},{id:'service_botox',name:'Ботокс для волос',price:3000,duration:150,description:'Восстановление, питание и красивый блеск.',active:true},{id:'service_restore',name:'Восстановление волос',price:2500,duration:120,description:'Интенсивный уход для повреждённых волос.',active:true},{id:'service_style',name:'Уход и укладка',price:1500,duration:90,description:'Уход и укладка для завершённого образа.',active:true}];
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch(e){return d}},clone=x=>JSON.parse(JSON.stringify(x));
function merge(a,b){a=clone(a);if(!b)return a;Object.keys(b).forEach(k=>a[k]&&typeof a[k]==='object'&&!Array.isArray(a[k])&&b[k]&&typeof b[k]==='object'&&!Array.isArray(b[k])?a[k]=merge(a[k],b[k]):a[k]=b[k]);return a}
function settings(){return merge(DEF,read(K.settings,{}))}function services(){const s=read(K.services,null);return Array.isArray(s)&&s.length?s:DEFAULT_SERVICES}function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function pad(n){return String(n).padStart(2,'0')}function today(){const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}function mins(t){const [h,m]=String(t).split(':').map(Number);return h*60+m}
function applySite(){const s=settings(),x=s.site||DEF.site;
 const h1=$('.hero h1');if(h1)h1.innerHTML=`${esc(x.heroTitle)} <span>${esc(x.heroAccent)}</span>`;
 const setImage=(selectors,src,alt)=>{const nodes=[];selectors.forEach(q=>$$(`${q}`).forEach(e=>nodes.push(e)));const unique=[...new Set(nodes)];unique.forEach(e=>{if(e.tagName==='IMG'){if(src){e.src=src;e.alt=alt||e.alt||'';e.style.display='block'}else{e.removeAttribute('src');e.style.display='none'}}else{if(src){e.style.backgroundImage=`url("${src.replace(/"/g,'&quot;')}")`;e.classList.add('has-site-image')}else{e.style.backgroundImage='';e.classList.remove('has-site-image')}}})};
 setImage(['.hero-card img','.hero-visual img','.hero-image img','.hero-photo img','.hero-media img','[data-hero-image]'],x.heroImage,'LUMI HAIR');
 setImage(['.about-image img','.about-visual img','.about-photo img','.about-media img','[data-about-image]'],x.aboutImage,'LUMI HAIR');
 const map={'.hero-label':x.heroLabel,'.hero-text':x.heroText,'.hero-note':x.heroNote,'.about-section .section-label':x.aboutLabel,'.about-signature span':x.aboutSignature,'.contact-main p':x.contactText};Object.entries(map).forEach(([q,v])=>{const e=$(q);if(e)e.textContent=v});
 const about=$('.about-content h2');if(about)about.innerHTML=`${esc(x.aboutTitle)} <span>${esc(x.aboutAccent)}</span>`;const ps=$$('.about-content>p');if(ps[0])ps[0].textContent=x.aboutText1;if(ps[1])ps[1].textContent=x.aboutText2;
 const stat=$('.hero-card-top strong');if(stat)stat.textContent=x.heroStat;const statText=$('.hero-card-top span');if(statText)statText.textContent=x.heroStatText;const heroPrimary=$('.hero [data-open-booking]');if(heroPrimary)heroPrimary.textContent=x.heroButton;const heroSecondary=$('.hero a[href*=\"portfolio\"], .hero [data-scroll=\"portfolio\"]');if(heroSecondary)heroSecondary.textContent=x.heroSecondaryButton;
 const phone=$('.contact-item[href^="tel:"]');if(phone){phone.href='tel:'+String(s.phone).replace(/\D/g,'');const st=phone.querySelector('strong');if(st)st.textContent=s.phone}const ci=$$('.contact-item');if(ci[1]?.querySelector('strong'))ci[1].querySelector('strong').textContent=s.address;if(ci[2]?.querySelector('strong'))ci[2].querySelector('strong').textContent=`${s.startTime}–${s.endTime}`;
 const title=$('title');if(title)title.textContent=x.seoTitle;const md=$('meta[name="description"]');if(md)md.content=x.seoDescription;
 renderBenefits(x.benefits);renderServices();renderPortfolio(x.portfolio);renderReviews(x.reviews);renderFaq(x.faq);document.querySelectorAll('.footer .logo-sub').forEach(e=>e.textContent='HAIR');
}
function renderBenefits(a){const e=$('.benefits-grid');if(e)e.innerHTML=(a||[]).map(x=>`<article class="benefit"><div class="benefit-number">${esc(x.number)}</div><div><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></div></article>`).join('')}
function renderServices(){const a=services().filter(x=>x.active!==false),g=$('.services-grid'),p=$('.price-list');if(g)g.innerHTML=a.map((x,i)=>`<article class="service-card" data-service-card data-service="${esc(x.name)}"><div class="service-top"><span class="service-number">${String(i+1).padStart(2,'0')}</span></div><h3>${esc(x.name)}</h3><p>${esc(x.description||'Профессиональный уход за волосами.')}</p><div class="service-bottom"><span class="service-price">от ${Number(x.price).toLocaleString('ru-RU')} ₽</span><button class="service-link" type="button" data-open-booking data-service="${esc(x.name)}">Записаться →</button></div></article>`).join('');if(p)p.innerHTML=a.map(x=>`<div class="price-item"><div class="price-info"><h3>${esc(x.name)}</h3><p>${esc(x.description||'')}</p></div><div class="price-value">от ${Number(x.price).toLocaleString('ru-RU')} ₽</div></div>`).join('');renderBookingOptions();bindServiceCards()}
function renderPortfolio(a){const e=$('.portfolio-grid');if(e)e.innerHTML=(a||[]).map((x,i)=>`<article class="portfolio-item ${i===0?'portfolio-large':''}"><div class="portfolio-placeholder">${x.image?`<img src="${esc(x.image)}" alt="${esc(x.title||'Работа')}" loading="lazy" style="width:100%;height:100%;object-fit:cover;display:block;">`:`<span>Фото работы</span>`}</div><div class="portfolio-info"><span>${esc(x.category)}</span><strong>${esc(x.title)}</strong></div></article>`).join('')}
function renderReviews(a){const e=$('.reviews-grid');if(e)e.innerHTML=(a||[]).map(x=>`<article class="review-card"><div class="review-stars">★★★★★</div><p>«${esc(x.text)}»</p><div class="review-author"><span class="review-avatar">${x.avatar?`<img src="${esc(x.avatar)}" alt="${esc(x.name||'')}" loading="lazy" style="width:100%;height:100%;object-fit:cover;display:block;">`:`${esc((x.name||'L')[0])}`}</span><div><strong>${esc(x.name)}</strong><span>${esc(x.service)}</span></div></div></article>`).join('')}
function renderFaq(a){const e=$('.faq-list');if(!e)return;e.innerHTML=(a||[]).map(x=>`<article class="faq-item"><button type="button" class="faq-question"><span>${esc(x.question)}</span><span class="faq-icon">+</span></button><div class="faq-answer"><p>${esc(x.answer)}</p></div></article>`).join('');bindFaq()}
function bindFaq(){$$('.faq-question').forEach(q=>q.onclick=()=>{const i=q.closest('.faq-item');const on=i.classList.contains('active');$$('.faq-item').forEach(x=>x.classList.remove('active'));if(!on)i.classList.add('active')})}
function renderBookingOptions(selected=''){const s=$('#bookingService');if(!s)return;s.innerHTML='<option value="">Выберите услугу</option>'+services().filter(x=>x.active!==false).map(x=>`<option value="${esc(x.name)}">${esc(x.name)}</option>`).join('');if(selected)s.value=selected}
const modal=$('#bookingModal'),form=$('#bookingForm'),dateEl=$('#bookingDate'),timeEl=$('#bookingTime'),slots=$('#timeSlots'),serviceEl=$('#bookingService');
function openModal(m){if(m)m.classList.add('active')}function closeModal(m){if(m)m.classList.remove('active')}
function phoneMask(e){let v=e.target.value.replace(/\D/g,'');if(v.startsWith('8'))v='7'+v.slice(1);if(v&&!v.startsWith('7'))v='7'+v;if(!v){e.target.value='';return}v=v.slice(0,11);let r='+7';if(v.length>1)r+=' ('+v.slice(1,4);if(v.length>=4)r+=')';if(v.length>4)r+=' '+v.slice(4,7);if(v.length>7)r+='-'+v.slice(7,9);if(v.length>9)r+='-'+v.slice(9,11);e.target.value=r}$('#bookingPhone')?.addEventListener('input',phoneMask);
function renderSlots(){if(!slots)return;const s=settings(),start=mins(s.startTime),end=mins(s.endTime),step=+s.slotDuration||30,dateV=dateEl.value,service=services().find(x=>x.name===serviceEl?.value)||{duration:30},apps=read(K.appointments,[]).filter(x=>x.date===dateV&&x.status!=='cancelled');slots.innerHTML='';for(let t=start;t<=end;t+=step){const tm=`${pad(Math.floor(t/60))}:${pad(t%60)}`,b=document.createElement('button');b.type='button';b.className='time-slot';b.textContent=tm;const overlap=apps.some(x=>t<mins(x.time)+(x.duration||30)&&t+(service.duration||30)>mins(x.time));if(dateV===today()){const n=new Date();if(t<=n.getHours()*60+n.getMinutes())b.disabled=true}if(overlap)b.disabled=true;if(new Date(dateV+'T12:00:00').getDay()===0)b.disabled=true;b.onclick=()=>{$$('.time-slot').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');timeEl.value=tm;summary()};slots.appendChild(b)}}
function summary(){const a=$('#summaryService'),b=$('#summaryDate'),c=$('#summaryTime');if(a)a.textContent=serviceEl?.value||'—';if(b)b.textContent=dateEl?.value?new Date(dateEl.value+'T12:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'}):'—';if(c)c.textContent=timeEl?.value||'—'}
function openBooking(s=''){renderBookingOptions(s);if(serviceEl)serviceEl.value=s;if(dateEl){dateEl.min=today();const d=new Date();d.setDate(d.getDate()+(+settings().advanceBooking||30));dateEl.max=`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;if(!dateEl.value)dateEl.value=today()}if(timeEl)timeEl.value='';if(form)form.hidden=false;$('#bookingSuccess')?.setAttribute('hidden','');renderSlots();summary();openModal(modal)}
document.addEventListener('click',e=>{const o=e.target.closest('[data-open-booking]');if(o){e.preventDefault();openBooking(o.dataset.service||'');return}const c=e.target.closest('[data-close-modal]');if(c){closeModal(c.closest('.modal'));return}if(e.target.classList.contains('modal-overlay'))closeModal(e.target.closest('.modal'))});document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('.modal.active').forEach(closeModal)});dateEl?.addEventListener('change',()=>{timeEl.value='';renderSlots();summary()});serviceEl?.addEventListener('change',()=>{timeEl.value='';renderSlots();summary()});
function saveClient(b){let a=read(K.clients,[]),p=String(b.phone).replace(/\D/g,''),c=a.find(x=>p&&String(x.phone).replace(/\D/g,'')===p);if(!c)c={id:'client_'+Date.now().toString(36),name:b.name,phone:b.phone,email:'',notes:b.comment||'',bookings:0,totalSpent:0,lastVisit:'',createdAt:new Date().toISOString()};else{c.name=b.name;c.phone=b.phone}const i=a.findIndex(x=>x.id===c.id);if(i<0)a.push(c);else a[i]=c;localStorage.setItem(K.clients,JSON.stringify(a));return c}
form?.addEventListener('submit',e=>{e.preventDefault();const s=services().find(x=>x.name===serviceEl.value);if(!serviceEl.value||!dateEl.value||!timeEl.value||!$('#bookingName').value.trim())return;const ph=String($('#bookingPhone').value).replace(/\D/g,'');if(ph.length!==11)return;const apps=read(K.appointments,[]);const t=mins(timeEl.value);if(apps.some(x=>x.date===dateEl.value&&x.status!=='cancelled'&&t<mins(x.time)+(x.duration||30)&&t+(s?.duration||30)>mins(x.time)))return renderSlots();const b={id:'appointment_'+Date.now().toString(36),clientId:'',clientName:$('#bookingName').value.trim(),name:$('#bookingName').value.trim(),phone:$('#bookingPhone').value,email:'',service:s.name,date:dateEl.value,time:timeEl.value,price:+s.price||0,duration:+s.duration||30,comment:$('#bookingComment')?.value||'',status:'new',source:'website',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};b.clientId=saveClient(b).id;apps.push(b);localStorage.setItem(K.appointments,JSON.stringify(apps));localStorage.setItem(K.legacy,JSON.stringify(apps));form.hidden=true;const ok=$('#bookingSuccess');if(ok)ok.hidden=false;$('#successService')&&(($('#successService').textContent=b.service));$('#successDate')&&(($('#successDate').textContent=b.date));$('#successTime')&&(($('#successTime').textContent=b.time));window.dispatchEvent(new CustomEvent('lumiHairBookingCreated',{detail:b}))});
function bindServiceCards(){$$('[data-service-card]').forEach(c=>c.onclick=e=>{if(e.target.closest('[data-open-booking]'))return;const b=$('#serviceModal');if(b){const s=services().find(x=>x.name===c.dataset.service);$('#serviceModalTitle')&&( $('#serviceModalTitle').textContent=s?.name||'Услуга');$('#serviceModalDescription')&&( $('#serviceModalDescription').textContent=s?.description||'');const btn=b.querySelector('[data-open-booking]');if(btn)btn.dataset.service=s?.name||'';openModal(b)}})}
const pre=$('#preloader');window.addEventListener('load',()=>setTimeout(()=>pre?.classList.add('hidden'),300));const year=$('#footerYear');if(year)year.textContent=new Date().getFullYear();const burger=$('#burger'),nav=$('#nav');burger?.addEventListener('click',()=>{burger.classList.toggle('active');nav?.classList.toggle('active')});$$('.nav-link').forEach(x=>x.onclick=()=>nav?.classList.remove('active'));
window.addEventListener('storage',e=>{if([K.settings,K.services,K.appointments].includes(e.key)){applySite();renderSlots()}});window.addEventListener('lumiHairSettingsUpdated',()=>{applySite();renderSlots()});applySite();bindFaq();
window.LumiHair={getAppointments:()=>read(K.appointments,[]),getClients:()=>read(K.clients,[]),getServices:services,getSettings:settings,refreshSite:applySite};
});
